import { Language } from '../types';

export const ADVISORY_COPY: Record<Language, {
  title: string; badge: string; description: string; readAloud: string; stopAudio: string; selectCrop: string; growthStage: string; panchayatSoil: string; soilTexture: string; priority: string; recommendation: string; why: string; irrigation: string; rule: string; pest: string; organic: string; fertilizer: string; saving: string; harvest: string; market: string; validated: string; validity: string; voiceSummary: string;
}> = {
  en: { title: 'Crop Protection & Agronomic Advisory', badge: 'Weather-Triggered', description: 'Phenological and soil-moisture recommendations calibrated to current Panchayat precipitation forecasts', readAloud: 'Read Aloud', stopAudio: 'Stop Voice Audio', selectCrop: 'Select Target Crop', growthStage: 'Crop Growth Stage', panchayatSoil: 'Panchayat Soil / Elevation', soilTexture: 'Soil Texture Class', priority: "Today's Priority Recommendation", recommendation: 'Priority Recommendation', why: 'Why this advisory was generated:', irrigation: 'Irrigation & Water Management', rule: 'Rule of thumb:', pest: 'Pest & Disease Biological Shield', organic: 'Organic Alternative:', fertilizer: 'Fertilizer & Nutrient Timing', saving: 'Financial Saving:', harvest: 'Harvest Protection & Post-Harvest Storage', market: 'Market Link:', validated: 'Validated by Krishi Vigyan Kendra (KVK) Agronomist Ruleset & ICAR guidelines.', validity: 'Validity: 48 Hours', voiceSummary: "Today's priority action" },
  hi: { title: 'फसल सुरक्षा और कृषि परामर्श', badge: 'मौसम आधारित', description: 'वर्तमान पंचायत वर्षा पूर्वानुमान के अनुसार फसल अवस्था और मिट्टी की नमी पर आधारित सलाह', readAloud: 'आवाज़ में सुनें', stopAudio: 'आवाज़ रोकें', selectCrop: 'लक्षित फसल चुनें', growthStage: 'फसल की वृद्धि अवस्था', panchayatSoil: 'पंचायत मिट्टी / ऊंचाई', soilTexture: 'मिट्टी का प्रकार', priority: 'आज की प्राथमिक सलाह', recommendation: 'प्राथमिक सलाह', why: 'यह सलाह क्यों दी गई:', irrigation: 'सिंचाई और जल प्रबंधन', rule: 'मुख्य नियम:', pest: 'कीट और रोग सुरक्षा', organic: 'जैविक विकल्प:', fertilizer: 'उर्वरक और पोषक तत्व का समय', saving: 'आर्थिक बचत:', harvest: 'कटाई सुरक्षा और कटाई के बाद भंडारण', market: 'बाजार संपर्क:', validated: 'कृषि विज्ञान केंद्र (KVK) के नियमों और ICAR दिशानिर्देशों से सत्यापित।', validity: 'वैधता: 48 घंटे', voiceSummary: 'आज की प्राथमिक कार्रवाई' },
  bn: { title: 'ফসল সুরক্ষা ও কৃষি পরামর্শ', badge: 'আবহাওয়া-ভিত্তিক', description: 'বর্তমান পঞ্চায়েতের বৃষ্টির পূর্বাভাস অনুযায়ী ফসলের বৃদ্ধি ও মাটির আর্দ্রতার পরামর্শ', readAloud: 'শুনুন', stopAudio: 'ভয়েস থামান', selectCrop: 'লক্ষ্য ফসল বাছুন', growthStage: 'ফসলের বৃদ্ধির দশা', panchayatSoil: 'পঞ্চায়েতের মাটি / উচ্চতা', soilTexture: 'মাটির ধরন', priority: 'আজকের জরুরি পরামর্শ', recommendation: 'প্রধান পরামর্শ', why: 'এই পরামর্শের কারণ:', irrigation: 'সেচ ও জল ব্যবস্থাপনা', rule: 'মূল নিয়ম:', pest: 'পোকামাকড় ও রোগ সুরক্ষা', organic: 'জৈব বিকল্প:', fertilizer: 'সার ও পুষ্টি প্রয়োগের সময়', saving: 'আর্থিক সাশ্রয়:', harvest: 'ফসল কাটা ও কাটার পর সংরক্ষণ', market: 'বাজার সংযোগ:', validated: 'কৃষি বিজ্ঞান কেন্দ্র (KVK) নিয়ম ও ICAR নির্দেশিকা দ্বারা যাচাই করা।', validity: 'মেয়াদ: ৪৮ ঘণ্টা', voiceSummary: 'আজকের প্রধান করণীয়' }
};

export const ADVISORY_REASONS: Record<string, Record<Language, string>> = {
  'adv-paddy-veg-01': { en: 'Hyperlocal radar confirms 42.5mm rain cell converging over the Panchayat. Unregulated water retention causes premature tiller abortion.', hi: 'हाइपरलोकल रडार पंचायत के ऊपर 42.5 मिमी वर्षा सेल की पुष्टि करता है। अनियंत्रित जलभराव से कल्ले समय से पहले नष्ट हो सकते हैं।', bn: 'হাইপারলোকাল রাডার পঞ্চায়েতের ওপর ৪২.৫ মিমি বৃষ্টির মেঘ জমার নিশ্চয়তা দিয়েছে। অনিয়ন্ত্রিত জল জমলে পাশকাটি অকালে নষ্ট হতে পারে।' },
  'adv-mustard-sow-02': { en: 'Soil saturation index is currently 74%; early sowing into saturated furrows can reduce germination by 35%.', hi: 'मिट्टी की संतृप्ति 74% है; बहुत गीली क्यारियों में जल्दी बुवाई करने से अंकुरण 35% तक घट सकता है।', bn: 'মাটির জলধারণ সূচক এখন ৭৪%; অতিরিক্ত ভেজা জমিতে আগে বীজ বুনলে অঙ্কুরোদ্গম ৩৫% কমতে পারে।' },
  'adv-potato-tub-03': { en: 'Downscaled micro-weather models predict dew duration above 9.5 hours, crossing the critical Late Blight threshold.', hi: 'स्थानीय मौसम मॉडल 9.5 घंटे से अधिक ओस की अवधि बता रहे हैं, जो पछेती झुलसा रोग की गंभीर सीमा पार करती है।', bn: 'স্থানীয় আবহাওয়া মডেল ৯.৫ ঘণ্টার বেশি শিশিরের পূর্বাভাস দিচ্ছে, যা নাবী ধসা রোগের ঝুঁকির সীমা ছাড়িয়ে যায়।' },
  'adv-tomato-flow-04': { en: 'High wind velocity can strip blossoms; Boron fortification strengthens pedicel attachment.', hi: 'तेज हवा फूलों को गिरा सकती है; बोरॉन का प्रयोग डंठल को मजबूत करता है।', bn: 'প্রবল বাতাস ফুল ঝরিয়ে দিতে পারে; বোরন প্রয়োগে ফুলের ডাঁটা শক্ত হয়।' }
};
