import { Language } from '../types';

type AuthCopy = {
  farmer: { badge: string; title: string; description: string; listen: string; stop: string; signIn: string; register: string; mobile: string; sendOtp: string; resendOtp: string; enterOtp: string; panchayat: string; land: string; crop: string; alertChannel: string; continue: string; welcome: string };
  consumer: { badge: string; title: string; description: string; signIn: string; register: string; signInWith: string; mobile: string; email: string; getOtp: string; resend: string; buyerType: string; city: string; pincode: string; continue: string };
  fpo: { badge: string; title: string; description: string; signIn: string; register: string; cin: string; phone: string; sendOtp: string; resend: string; district: string; members: string; continue: string };
  government: { badge: string; title: string; description: string; email: string; employee: string; pin: string; department: string; jurisdiction: string; verify: string; continue: string };
};

export const AUTH_HUB_COPY: Record<Language, { badge: string; title: string; description: string; isolation: string; active: string; farmer: string; consumer: string; fpo: string; government: string }> = {
  en: { badge: 'Multi-Stakeholder Identity Hub', title: 'Select Your Stakeholder Portal', description: 'Choose the login experience designed for your role in the agricultural ecosystem.', isolation: 'Farmers, consumers, FPOs, and government users receive separate workflows and access controls.', active: 'Active Portal View', farmer: 'Farmer Portal', consumer: 'Consumer Portal', fpo: 'FPO Co-op Portal', government: 'Government Portal' },
  hi: { badge: 'बहु-हितधारक पहचान केंद्र', title: 'अपना पोर्टल चुनें', description: 'कृषि व्यवस्था में अपनी भूमिका के अनुसार लॉगिन अनुभव चुनें।', isolation: 'किसान, उपभोक्ता, FPO और सरकारी उपयोगकर्ताओं को अलग कार्यप्रवाह और अनुमति मिलती है।', active: 'सक्रिय पोर्टल', farmer: 'किसान पोर्टल', consumer: 'उपभोक्ता पोर्टल', fpo: 'FPO सहकारी पोर्टल', government: 'सरकारी पोर्टल' },
  bn: { badge: 'বহু-অংশীজন পরিচয় কেন্দ্র', title: 'আপনার পোর্টাল বেছে নিন', description: 'কৃষি ব্যবস্থায় আপনার ভূমিকার জন্য তৈরি লগইন অভিজ্ঞতা বেছে নিন।', isolation: 'কৃষক, ভোক্তা, FPO এবং সরকারি ব্যবহারকারীদের আলাদা কাজ ও অনুমতি দেওয়া হয়।', active: 'সক্রিয় পোর্টাল', farmer: 'কৃষক পোর্টাল', consumer: 'ভোক্তা পোর্টাল', fpo: 'FPO সমবায় পোর্টাল', government: 'সরকারি পোর্টাল' }
};

export const LISTING_COPY: Record<Language, { badge: string; title: string; description: string; back: string; listingAs: string; name: string; category: string; quantity: string; unit: string; price: string; harvestDate: string; village: string; district: string; organic: string; details: string; camera: string; upload: string; photoNote: string; publish: string; placeholderName: string; placeholderVillage: string }> = {
  en: { badge: 'Farmer Marketplace', title: 'List a fresh harvest', description: 'Share your crop details so nearby consumers can order directly from you.', back: 'Marketplace', listingAs: 'Listing as', name: 'Crop or product name', category: 'Category', quantity: 'Available quantity', unit: 'Unit', price: 'Price per unit (INR)', harvestDate: 'Harvest date', village: 'Village or pickup point', district: 'District', organic: 'Grown using organic practices', details: 'Crop photo', camera: 'Take photo', upload: 'Upload photo', photoNote: 'Use your phone camera or choose a photo from your device.', publish: 'Publish listing', placeholderName: 'e.g. Fresh brinjal', placeholderVillage: 'Your village' },
  hi: { badge: 'किसान मार्केटप्लेस', title: 'ताजा फसल सूचीबद्ध करें', description: 'अपनी फसल का विवरण साझा करें ताकि स्थानीय उपभोक्ता सीधे आपसे ऑर्डर कर सकें।', back: 'मार्केटप्लेस', listingAs: 'सूची किसके नाम से', name: 'फसल या उत्पाद की फोटो', category: 'श्रेणी', quantity: 'उपलब्ध मात्रा', unit: 'इकाई', price: 'प्रति इकाई कीमत (INR)', harvestDate: 'कटाई की तारीख', village: 'गांव या पिकअप स्थान', district: 'जिला', organic: 'जैविक तरीके से उगाई गई', details: 'फसल की फोटो', camera: 'फोटो लें', upload: 'फोटो अपलोड करें', photoNote: 'फोन का कैमरा खोलें या डिवाइस से फोटो चुनें।', publish: 'सूची प्रकाशित करें', placeholderName: 'जैसे ताजा बैंगन', placeholderVillage: 'आपका गांव' },
  bn: { badge: 'কৃষক মার্কেটপ্লেস', title: 'তাজা ফসলের তালিকা দিন', description: 'ফসলের বিবরণ দিন যাতে কাছের ক্রেতারা সরাসরি আপনার কাছ থেকে অর্ডার করতে পারেন।', back: 'মার্কেটপ্লেস', listingAs: 'তালিকা যার নামে', name: 'ফসল বা পণ্যের ছবি', category: 'বিভাগ', quantity: 'উপলব্ধ পরিমাণ', unit: 'একক', price: 'প্রতি এককের দাম (INR)', harvestDate: 'ফসল কাটার তারিখ', village: 'গ্রাম বা পিকআপ স্থান', district: 'জেলা', organic: 'জৈব পদ্ধতিতে উৎপাদিত', details: 'ফসলের ছবি', camera: 'ছবি তুলুন', upload: 'ছবি আপলোড করুন', photoNote: 'ফোনের ক্যামেরা খুলুন বা ডিভাইস থেকে ছবি বেছে নিন।', publish: 'তালিকা প্রকাশ করুন', placeholderName: 'যেমন তাজা বেগুন', placeholderVillage: 'আপনার গ্রাম' }
};

export const AUTH_COPY: Record<Language, AuthCopy> = {
  en: {
    farmer: { badge: 'Dedicated Farmer & Producer Gateway', title: 'Farmer Portal Login', description: 'Log in with your registered mobile OTP to view local weather forecasts, disaster warnings, and manage direct crop sales.', listen: 'Listen Instructions', stop: 'Stop Voice Prompt', signIn: 'Sign In with Mobile OTP', register: 'Register New Farmer', mobile: 'Registered Farmer Mobile Number', sendOtp: 'Send OTP', resendOtp: 'Resend OTP', enterOtp: 'Enter 4-Digit OTP', panchayat: 'Current Gram Panchayat Area', land: 'Cultivated Land (Acres)', crop: 'Primary Crop', alertChannel: 'Preferred Alert Channel', continue: 'Continue to Farmer Dashboard', welcome: 'Welcome' },
    consumer: { badge: 'Fair-Trade Direct Farm Marketplace', title: 'Consumer & Buyer Marketplace Login', description: 'Connect directly with verified local growers and order fresh, traceable harvests at fair prices.', signIn: 'Buyer Sign In', register: 'Create Consumer Account', signInWith: 'Sign In With', mobile: 'Mobile OTP', email: 'Email Passcode', getOtp: 'Get OTP', resend: 'Resend', buyerType: 'Buyer Type', city: 'Delivery City', pincode: 'Pincode', continue: 'Continue to Marketplace' },
    fpo: { badge: 'FPO Enterprise & Cooperative Network', title: 'FPO Cooperative Portal Login', description: 'Review member operations, agricultural risk, and marketplace data for your producer organization.', signIn: 'FPO Director Sign In', register: 'Register New FPO / Cooperative', cin: 'FPO Corporate Identity Number or Society Registration Number', phone: 'Authorized Executive Mobile Number', sendOtp: 'Send 2FA OTP', resend: 'Resend', district: 'Lead Operating District', members: 'Member Farmers Enrolled', continue: 'Continue to Admin Dashboard' },
    government: { badge: 'Agricultural Agromet Authority', title: 'Government & Agromet Oversight Portal', description: 'Monitor multi-panchayat agricultural risk, disaster conditions, and marketplace data.', email: 'Government Official Email', employee: 'Government Employee / Badge Code', pin: 'Security PIN / Token', department: 'Department Division', jurisdiction: 'Assigned District Jurisdiction', verify: 'Verify Security Token', continue: 'Continue to Admin Dashboard' }
  },
  hi: {
    farmer: { badge: 'किसान और उत्पादक प्रवेश द्वार', title: 'किसान पोर्टल लॉगिन', description: 'स्थानीय मौसम पूर्वानुमान, आपदा चेतावनी देखने और फसल बिक्री प्रबंधित करने के लिए पंजीकृत मोबाइल OTP से लॉगिन करें।', listen: 'निर्देश सुनें', stop: 'आवाज़ रोकें', signIn: 'मोबाइल OTP से लॉगिन', register: 'नया किसान पंजीकृत करें', mobile: 'पंजीकृत किसान मोबाइल नंबर', sendOtp: 'OTP भेजें', resendOtp: 'OTP फिर भेजें', enterOtp: '4 अंकों का OTP दर्ज करें', panchayat: 'वर्तमान ग्राम पंचायत क्षेत्र', land: 'कृषि भूमि (एकड़)', crop: 'मुख्य फसल', alertChannel: 'पसंदीदा चेतावनी माध्यम', continue: 'किसान डैशबोर्ड पर जाएं', welcome: 'स्वागत है' },
    consumer: { badge: 'सीधा किसान बाजार', title: 'उपभोक्ता और खरीदार मार्केटप्लेस लॉगिन', description: 'सत्यापित स्थानीय किसानों से सीधे जुड़ें और ताजा, ट्रेस योग्य फसल उचित कीमत पर ऑर्डर करें।', signIn: 'खरीदार लॉगिन', register: 'उपभोक्ता खाता बनाएं', signInWith: 'लॉगिन माध्यम', mobile: 'मोबाइल OTP', email: 'ईमेल पासकोड', getOtp: 'OTP लें', resend: 'फिर भेजें', buyerType: 'खरीदार का प्रकार', city: 'डिलीवरी शहर', pincode: 'पिनकोड', continue: 'मार्केटप्लेस पर जाएं' },
    fpo: { badge: 'FPO और सहकारी नेटवर्क', title: 'FPO सहकारी पोर्टल लॉगिन', description: 'अपने उत्पादक संगठन के सदस्य संचालन, कृषि जोखिम और बाजार डेटा की समीक्षा करें।', signIn: 'FPO निदेशक लॉगिन', register: 'नया FPO / सहकारी पंजीकृत करें', cin: 'FPO कॉर्पोरेट पहचान या सोसायटी पंजीकरण नंबर', phone: 'अधिकृत कार्यकारी मोबाइल नंबर', sendOtp: '2FA OTP भेजें', resend: 'फिर भेजें', district: 'मुख्य संचालन जिला', members: 'पंजीकृत किसान सदस्य', continue: 'प्रशासन डैशबोर्ड पर जाएं' },
    government: { badge: 'कृषि और मौसम प्राधिकरण', title: 'सरकारी और मौसम निगरानी पोर्टल', description: 'बहु-पंचायत कृषि जोखिम, आपदा स्थिति और बाजार डेटा की निगरानी करें।', email: 'सरकारी अधिकारी ईमेल', employee: 'सरकारी कर्मचारी / बैज कोड', pin: 'सुरक्षा PIN / टोकन', department: 'विभागीय प्रभाग', jurisdiction: 'निर्धारित जिला क्षेत्र', verify: 'सुरक्षा टोकन सत्यापित करें', continue: 'प्रशासन डैशबोर्ड पर जाएं' }
  },
  bn: {
    farmer: { badge: 'কৃষক ও উৎপাদক প্রবেশদ্বার', title: 'কৃষক পোর্টাল লগইন', description: 'স্থানীয় আবহাওয়া, দুর্যোগ সতর্কতা দেখতে এবং ফসল বিক্রি পরিচালনা করতে নিবন্ধিত মোবাইল OTP দিয়ে লগইন করুন।', listen: 'নির্দেশ শুনুন', stop: 'ভয়েস থামান', signIn: 'মোবাইল OTP দিয়ে লগইন', register: 'নতুন কৃষক নিবন্ধন', mobile: 'নিবন্ধিত কৃষকের মোবাইল নম্বর', sendOtp: 'OTP পাঠান', resendOtp: 'আবার OTP পাঠান', enterOtp: '৪ সংখ্যার OTP দিন', panchayat: 'বর্তমান গ্রাম পঞ্চায়েত এলাকা', land: 'চাষের জমি (একর)', crop: 'প্রধান ফসল', alertChannel: 'পছন্দের সতর্কতা মাধ্যম', continue: 'কৃষক ড্যাশবোর্ডে যান', welcome: 'স্বাগতম' },
    consumer: { badge: 'সরাসরি কৃষক বাজার', title: 'ভোক্তা ও ক্রেতা মার্কেটপ্লেস লগইন', description: 'যাচাই করা স্থানীয় কৃষকদের সঙ্গে সরাসরি যুক্ত হয়ে ন্যায্য দামে তাজা ফসল অর্ডার করুন।', signIn: 'ক্রেতা লগইন', register: 'ভোক্তা অ্যাকাউন্ট তৈরি করুন', signInWith: 'লগইন পদ্ধতি', mobile: 'মোবাইল OTP', email: 'ইমেল পাসকোড', getOtp: 'OTP নিন', resend: 'আবার পাঠান', buyerType: 'ক্রেতার ধরন', city: 'ডেলিভারি শহর', pincode: 'পিনকোড', continue: 'মার্কেটপ্লেসে যান' },
    fpo: { badge: 'FPO ও সমবায় নেটওয়ার্ক', title: 'FPO সমবায় পোর্টাল লগইন', description: 'আপনার উৎপাদক সংগঠনের সদস্য পরিচালনা, কৃষি ঝুঁকি এবং বাজার তথ্য পর্যালোচনা করুন।', signIn: 'FPO পরিচালক লগইন', register: 'নতুন FPO / সমবায় নিবন্ধন', cin: 'FPO কর্পোরেট পরিচয় বা সমিতি নিবন্ধন নম্বর', phone: 'অনুমোদিত আধিকারিকের মোবাইল নম্বর', sendOtp: '2FA OTP পাঠান', resend: 'আবার পাঠান', district: 'প্রধান কার্যকরী জেলা', members: 'নিবন্ধিত কৃষক সদস্য', continue: 'অ্যাডমিন ড্যাশবোর্ডে যান' },
    government: { badge: 'কৃষি ও আবহাওয়া কর্তৃপক্ষ', title: 'সরকারি ও আবহাওয়া পর্যবেক্ষণ পোর্টাল', description: 'একাধিক পঞ্চায়েতের কৃষি ঝুঁকি, দুর্যোগ পরিস্থিতি এবং বাজার তথ্য পর্যবেক্ষণ করুন।', email: 'সরকারি আধিকারিকের ইমেল', employee: 'সরকারি কর্মী / ব্যাজ কোড', pin: 'নিরাপত্তা PIN / টোকেন', department: 'বিভাগীয় শাখা', jurisdiction: 'নির্ধারিত জেলা এলাকা', verify: 'নিরাপত্তা টোকেন যাচাই করুন', continue: 'অ্যাডমিন ড্যাশবোর্ডে যান' }
  }
};
